const users = [
  {
    id: {
      $oid: '64322066fc13ae373d69e034',
    },
    firstName: 'Tabbatha',
    lastNamt: 'Bidgood',
    email: 'tbidgood0@technorati.com',
    password: 'PHhj3D75',
    picturePath: 'http://dummyimage.com/196x100.png/5fa2dd/ffffff',
    friends: [],
    age: 64,
    location: 'Spanish Wells',
    occupation: 'Senior Developer',
    bio: 1,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e035',
    },
    firstName: 'Darcee',
    lastNamt: 'Dibden',
    email: 'ddibden1@elegantthemes.com',
    password: 'nVJCsy',
    picturePath: 'http://dummyimage.com/114x100.png/dddddd/000000',
    friends: [],
    age: 96,
    location: 'Cerenti',
    occupation: 'Media Manager II',
    bio: 2,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e036',
    },
    firstName: 'Chrystal',
    lastNamt: 'Drinan',
    email: 'cdrinan2@hatena.ne.jp',
    password: 'cMV7XsKdTlX',
    picturePath: 'http://dummyimage.com/224x100.png/ff4444/ffffff',
    friends: [],
    age: 49,
    location: 'Sitrah',
    occupation: 'Biostatistician IV',
    bio: 3,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e037',
    },
    firstName: 'Carolina',
    lastNamt: 'Peasnone',
    email: 'cpeasnone3@home.pl',
    password: 'm199BC',
    picturePath: 'http://dummyimage.com/107x100.png/cc0000/ffffff',
    friends: [],
    age: 63,
    location: 'Krasnogorodskoye',
    occupation: 'Account Executive',
    bio: 4,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e038',
    },
    firstName: 'Burnaby',
    lastNamt: 'Gerrard',
    email: 'bgerrard4@wisc.edu',
    password: 'BYXjG88FTnxq',
    picturePath: 'http://dummyimage.com/168x100.png/dddddd/000000',
    friends: [],
    age: 72,
    location: 'Wahawaha',
    occupation: 'Developer I',
    bio: 5,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e039',
    },
    firstName: 'Dar',
    lastNamt: 'Braybrookes',
    email: 'dbraybrookes5@mail.ru',
    password: 'Z4Ve9LHzX6K7',
    picturePath: 'http://dummyimage.com/235x100.png/5fa2dd/ffffff',
    friends: [],
    age: 97,
    location: 'Niyang',
    occupation: 'Senior Developer',
    bio: 6,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e03a',
    },
    firstName: 'Granthem',
    lastNamt: 'Waddilove',
    email: 'gwaddilove6@taobao.com',
    password: '7SKEGlvOzz',
    picturePath: 'http://dummyimage.com/141x100.png/cc0000/ffffff',
    friends: [],
    age: 9,
    location: 'Sydney',
    occupation: 'Computer Systems Analyst I',
    bio: 7,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e03b',
    },
    firstName: 'Hurley',
    lastNamt: 'Olivey',
    email: 'holivey7@tuttocitta.it',
    password: 'U3JeqpFWFl',
    picturePath: 'http://dummyimage.com/233x100.png/ff4444/ffffff',
    friends: [],
    age: 28,
    location: 'Shimeitang',
    occupation: 'Software Consultant',
    bio: 8,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e03c',
    },
    firstName: 'Buck',
    lastNamt: 'Brooke',
    email: 'bbrooke8@redcross.org',
    password: 'QcSU21m8lY',
    picturePath: 'http://dummyimage.com/107x100.png/cc0000/ffffff',
    friends: [],
    age: 21,
    location: 'Ciawi',
    occupation: 'Senior Editor',
    bio: 9,
    posts: [],
  },
  {
    id: {
      $oid: '64322066fc13ae373d69e03d',
    },
    firstName: 'Cairistiona',
    lastNamt: 'Cottle',
    email: 'ccottle9@tumblr.com',
    password: '1RqNA663Ct6',
    picturePath: 'http://dummyimage.com/211x100.png/dddddd/000000',
    friends: [],
    age: 50,
    location: 'Tomepampa',
    occupation: 'Cost Accountant',
    bio: 10,
    posts: [],
  },
];

module.exports = users;