const users = [
  {
    id: 'c338b895-fd37-42d4-892c-af5ddd8f5478',
    firstName: 'Nataniel',
    lastNamt: 'Hegge',
    email: 'nhegge0@who.int',
    password: 'hZws04',
    picturePath: 'http://dummyimage.com/103x100.png/ff4444/ffffff',
    friends: [],
    age: 13,
    location: 'Gorzyce',
    occupation: 'VP Marketing',
    bio: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    posts: [],
  },
  {
    id: '59ef6510-747b-4815-95f9-281b0418233e',
    firstName: 'Hammad',
    lastNamt: 'Barnsley',
    email: 'hbarnsley1@umich.edu',
    password: 'Q2FiUa',
    picturePath: 'http://dummyimage.com/245x100.png/dddddd/000000',
    friends: [],
    age: 87,
    location: 'Zhigong',
    occupation: 'Assistant Media Planner',
    bio: 'Praesent blandit lacinia erat.',
    posts: [],
  },
  {
    id: '34818ff5-7507-4b85-83c3-bfd43bb015e6',
    firstName: 'Ciro',
    lastNamt: 'Ladbury',
    email: 'cladbury2@forbes.com',
    password: 'BD9ska25xW',
    picturePath: 'http://dummyimage.com/203x100.png/ff4444/ffffff',
    friends: [],
    age: 38,
    location: 'Xiangxi',
    occupation: 'Web Developer II',
    bio: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    posts: [],
  },
  {
    id: '98e41da1-262e-455e-8bdb-7b70460ec296',
    firstName: 'Norrie',
    lastNamt: 'Gurr',
    email: 'ngurr3@nationalgeographic.com',
    password: 'vIP7s756',
    picturePath: 'http://dummyimage.com/155x100.png/ff4444/ffffff',
    friends: [],
    age: 15,
    location: 'Lanta Timur',
    occupation: 'Geologist II',
    bio: 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    posts: [],
  },
  {
    id: '8e92a4e0-45ef-40fa-950a-7b53f795895f',
    firstName: 'Fredric',
    lastNamt: 'Yarrall',
    email: 'fyarrall4@devhub.com',
    password: 'ST3hInUE',
    picturePath: 'http://dummyimage.com/250x100.png/ff4444/ffffff',
    friends: [],
    age: 35,
    location: 'Xinbu',
    occupation: 'Director of Sales',
    bio: 'Integer a nibh. In quis justo.',
    posts: [],
  },
  {
    id: '90790e66-b875-4dc1-8be1-9f0ad95444ed',
    firstName: 'Nessi',
    lastNamt: 'Airlie',
    email: 'nairlie5@ask.com',
    password: '5bmVAYeh72RQ',
    picturePath: 'http://dummyimage.com/242x100.png/5fa2dd/ffffff',
    friends: [],
    age: 38,
    location: 'Radymno',
    occupation: 'Data Coordinator',
    bio: 'Nullam sit amet turpis elementum ligula vehicula consequat.',
    posts: [],
  },
  {
    id: 'c6c2c71f-d9f2-45de-b674-c9fb290294b0',
    firstName: 'Margeaux',
    lastNamt: 'Willarton',
    email: 'mwillarton6@woothemes.com',
    password: '5jP3h5',
    picturePath: 'http://dummyimage.com/211x100.png/cc0000/ffffff',
    friends: [],
    age: 17,
    location: 'Finspång',
    occupation: 'Statistician III',
    bio: 'Vestibulum ac est lacinia nisi venenatis tristique.',
    posts: [],
  },
  {
    id: '1a7f8ca7-6d5b-4fee-b81a-dce4feaf5694',
    firstName: 'Collie',
    lastNamt: 'Easlea',
    email: 'ceaslea7@google.com',
    password: '1NdsXs',
    picturePath: 'http://dummyimage.com/250x100.png/ff4444/ffffff',
    friends: [],
    age: 46,
    location: 'Buenos Aires',
    occupation: 'Nurse Practicioner',
    bio: 'Vestibulum ac est lacinia nisi venenatis tristique.',
    posts: [],
  },
  {
    id: 'bc3031b6-d7fc-417e-a14b-d2f94463dab6',
    firstName: 'Jasun',
    lastNamt: 'Alecock',
    email: 'jalecock8@princeton.edu',
    password: '6415BT',
    picturePath: 'http://dummyimage.com/168x100.png/dddddd/000000',
    friends: [],
    age: 42,
    location: 'Banjar Dauhpangkung',
    occupation: 'Physical Therapy Assistant',
    bio: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',
    posts: [],
  },
  {
    id: 'c493c28a-f601-4526-8dd3-6e3042636125',
    firstName: 'Titus',
    lastNamt: 'Lukes',
    email: 'tlukes9@loc.gov',
    password: 'RXFVok',
    picturePath: 'http://dummyimage.com/105x100.png/ff4444/ffffff',
    friends: [],
    age: 5,
    location: 'Zelenodolsk',
    occupation: 'Safety Technician IV',
    bio: 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    posts: [],
  },
];

module.exports = users;
